#
# Dockerfile for locomotive_air_cleaner development environment
#
# Preconditions:
# 1. Ubuntu 24.04 installed on raspberry pi
# 2. docker installed on raspberry pi
# 3. git installed.
# 4. (optional) vnc installed and running
# 5. open sshd running 
# 6. If running on arm64 then ros-jazzy-arm64 image has been created and locally stored.
#
# To build an image with this (for arm64):
#
# docker build --platform linux/arm64 -t locomotive_air_cleaner_capstone-arm64 --load  --no-cache -f docker/Dockerfile
#
ARG ARCH
FROM osrf/ros:jazzy-desktop-full AS amd64
# comment out the line below when building on amd64
FROM ros-jazzy-arm64 AS arm64 

# Arguments for user setup
ARG USERNAME=ubuntu
ARG USER=$USERNAME
ARG UID=1000
ARG GID=1000

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_WS=/home/${USERNAME}/robot_ws
ENV TERM=linux
ENV ROS_DISTRO=jazzy
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Make default shell in Dockerfile bash instead of sh
SHELL ["/bin/bash", "-c"]


# Copy requirement files and install dependencies
COPY docker/requirements.txt .
RUN apt-get update && apt-get install --no-install-recommends -y $(cat requirements.txt)
RUN rm requirements.txt

RUN if id "$USERNAME" >/dev/null 2>&1; then \
        usermod --uid $UID --gid $GID $USERNAME; \
    fi && \
    groupmod --gid $GID $USERNAME || true && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

RUN ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "arm64" ]; then \
        curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.6.0/fixuid-0.6.0-linux-arm64.tar.gz | tar -C /usr/local/bin -xzf -; \
    elif [ "$ARCH" = "amd64" ]; then \
        curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.6.0/fixuid-0.6.0-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf -; \
    else \
        echo "Unsupported architecture: $ARCH" && exit 1; \
    fi && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $USER\n" > /etc/fixuid/config.yml



# Create a user with passwordless sudo
#RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN echo "export QT_X11_NO_MITSHM=1" >> /home/$USER/.bashrc

# Adds USER to dialout and plugdev group.
# This is needed to access the serial ports, for further references check
# the libserial documentation.
RUN sudo usermod -a -G dialout $USER
RUN sudo usermod -a -G plugdev $USER
RUN sudo usermod -a -G video $USER

USER $USER


# Switch to user
USER ${USERNAME}

# Adds to bashrc the ros jazzy overlay sourcing.
RUN echo "source /opt/ros/jazzy/setup.bash" >> /home/$USER/.bashrc

# Add OSRF key and repository (Ubuntu 24.04 method)
RUN sudo mkdir -p /etc/apt/keyrings && \
    curl -fsSL http://packages.osrfoundation.org/gazebo.key | sudo tee /etc/apt/keyrings/osrf-gpg.key > /dev/null

RUN echo "deb [signed-by=/etc/apt/keyrings/osrf-gpg.key] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

# Install Gazebo (Ignition)
RUN sudo apt update && sudo apt install -y \
    gz-ionic \
    ros-jazzy-gz-ros2-control \
    && sudo apt clean


# Create custom workspace
# RUN mkdir -p ${ROS_WS}/src

ENV EXERCISES_WS=/home/${USERNAME}/exercises_ws
RUN mkdir -p $EXERCISES_WS/src

# Install dependencies
RUN sudo apt-get update && \
    sudo apt-get install -y --no-install-recommends \
    ros-jazzy-navigation2 \
    ros-jazzy-turtle-nest \
    ros-jazzy-tf-transformations \
    && sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*


#  Install SSH without using `systemctl`
RUN sudo apt update && sudo apt install -y openssh-server && \
    sudo mkdir -p /var/run/sshd && \
    test -f /etc/ssh/ssh_host_rsa_key || sudo ssh-keygen -A && \
    sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config


#  Expose SSH port
EXPOSE 22

# Install Arduino IDE
# Install Arduino IDE (Supports ARM64 and AMD64)
RUN cd /tmp && \
    ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "arm64" ]; then \
        wget https://downloads.arduino.cc/arduino-1.8.19-linuxaarch64.tar.xz -O arduino.tar.xz; \
    elif [ "$ARCH" = "amd64" ]; then \
        wget https://downloads.arduino.cc/arduino-1.8.19-linux64.tar.xz -O arduino.tar.xz; \
    else \
        echo "Unsupported architecture: $ARCH" && exit 1; \
    fi && \
    tar -xf arduino.tar.xz && \
    sudo mv arduino-1.8.19 /opt/ && \
    cd /opt/arduino-1.8.19 && \
    sudo ./install.sh && \
    rm -rf /tmp/arduino.tar.xz

# Install Visual Studio Code
RUN cd /tmp && \
    sudo apt update && sudo apt install -y wget xdg-utils && \
    ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "amd64" ]; then \
        wget -O vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"; \
    elif [ "$ARCH" = "arm64" ]; then \
        wget -O vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64"; \
    else \
        echo "Unsupported architecture: $ARCH" && exit 1; \
    fi && \
    sudo dpkg -i vscode.deb && \
    rm -f vscode.deb

# Update system and initialize rosdep only if it hasn't been initialized
RUN sudo apt update && sudo apt upgrade -y && \
    if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then \
        sudo rosdep init; \
    else \
        echo "rosdep already initialized, skipping..."; \
    fi && \
    rosdep update


#  Ensure VS Code works by setting up a user directory
RUN mkdir -p /home/${USERNAME}/.vscode/extensions && \
    sudo chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vscode

#  Add script to install extensions at runtime
COPY docker/vscode_extensions.sh /usr/local/bin/vscode_extensions.sh
# RUN chmod +x /usr/local/bin/vscode_extensions.sh

# Register rosdep.yaml as a local source
# This is done for the robotics_essentials_ros2 to work for jazzy. In the humble
# version some of these dependencies could be pulled in from apt. Those packages
# don't exist for jazzy so we pull them from andino source (see rosdep.yaml).
#
RUN sudo mkdir -p /etc/ros/rosdep/sources.list.d/
RUN echo "yaml file://${ROS_WS}/rosdep.yaml" | sudo tee /etc/ros/rosdep/sources.list.d/50-custom-rosdeps.list
RUN sudo rosdep init || true
# Update rosdep to include the new source
RUN rosdep update

RUN cd ${ROS_WS}/src && \
    sudo apt-get update && \
    . /opt/ros/${ROS_DISTRO}/setup.bash && \
    cd .. && \
    rosdep install --from-paths src --ignore-src -r -y --rosdistro ${ROS_DISTRO} && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/* && \
    colcon build --symlink-install --packages-select andino_description && \
    colcon build --symlink-install

# Build exercises_ws
RUN cd ${EXERCISES_WS}/src && \
    sudo apt-get update && \
    . /opt/ros/${ROS_DISTRO}/setup.bash && \
    cd .. && \
    rosdep update && rosdep install --from-paths src --ignore-src -r -y --rosdistro ${ROS_DISTRO} && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/* && \
    colcon build --symlink-install

# Source ROS workspace automatically when new terminal is opened
RUN sudo echo ". /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
    sudo echo ". ${EXERCISES_WS}/install/setup.bash" >> ~/.bashrc && \
    sudo echo ". ${ROS_WS}/install/setup.bash" >> ~/.bashrc

WORKDIR /home/${USERNAME}/exercises_ws

# Source ROS in the main terminal
# COPY docker/ros_entrypoint.sh /ros_entrypoint.sh
# Clone custom repository

# Install LiDAR dependencies
RUN cd ${ROS_WS}/src && \
    git clone https://github.com/Slamtec/sllidar_ros2.git

RUN cd ${ROS_WS} && \
    .  /opt/ros/jazzy/setup.bash && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y && \
    colcon build --symlink-install
# Source environment
RUN echo "source ${ROS_WS}/install/setup.bash" >> /home/${USERNAME}/.bashrc


# Set working directory
WORKDIR ${ROS_WS}

# CMD ["/bin/bash"]
CMD ["/bin/bash", "-c", "ssh-keygen -A & /usr/sbin/sshd -D & /usr/local/bin/vscode_extensions.sh ; exec bash"]
# CMD ["/bin/bash", "-c", "exec bash"]

