controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    # Joint State Broadcaster - publishes joint states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Joint Trajectory Controller - accepts trajectory commands
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    allow_partial_joints_goal: false
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      
    # PID gains (tune these for your robot)
    gains:
      joint_1:
        p: 100.0
        i: 0.0
        d: 10.0
      joint_2:
        p: 100.0
        i: 0.0
        d: 10.0
      joint_3:
        p: 100.0
        i: 0.0
        d: 10.0
      joint_4:
        p: 100.0
        i: 0.0
        d: 10.0
