# Default pose sequence for load_tester analysis
# Usage: ros2 run writing_robot_control load_tester --analyze-sequence default_poses.yaml --movement-time 2.0

poses:
  - name: pose 0
    positions:
      shoulder_pan: 1.1679
      shoulder_lift: 2.60
      elbow_flex: 1.193
      wrist_flex: 2.6873
      wrist_roll: 1.01906
      pen_holder: 1.10

  - name: pose 1
    positions:
      shoulder_pan: 1.1679
      shoulder_lift: 2.50
      elbow_flex: 1.193
      wrist_flex: 2.4556
      wrist_roll: 0.92544
      pen_holder: 1.58

  - name: pose 2
    positions:
      shoulder_pan: 1.9874
      shoulder_lift: 2.50
      elbow_flex: 1.000
      wrist_flex: 1.5908
      wrist_roll: -1.4083
      pen_holder: 0.21

  - name: pose 3
    positions:
      shoulder_pan: 1.4533
      shoulder_lift: 2.56
      elbow_flex: 1.105
      wrist_flex: 1.2992
      wrist_roll: -0.3728
      pen_holder: 1.59

  - name: pose 4
    positions:
      shoulder_pan: 1.8125
      shoulder_lift: 2.56
      elbow_flex: 1.632
      wrist_flex: 2.4402
      wrist_roll: 1.1915
      pen_holder: 0.5

  - name: pose 5
    positions:
      shoulder_pan: 1.8125
      shoulder_lift: 2.56
      elbow_flex: 1.632
      wrist_flex: 2.4402
      wrist_roll: 1.1915
      pen_holder: 1.5