controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - pen_holder
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    # Allow some deviation for trajectory following
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    allow_partial_joints_goal: false
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      
      shoulder_pan:
        trajectory: 0.05
        goal: 0.02
      shoulder_lift:
        trajectory: 0.05
        goal: 0.02
      elbow_flex:
        trajectory: 0.05
        goal: 0.02
      wrist_flex:
        trajectory: 0.05
        goal: 0.02
      wrist_roll:
        trajectory: 0.05
        goal: 0.02
      pen_holder:
        trajectory: 0.02
        goal: 0.01
