controller_manager:
  ros__parameters:
    update_rate: 100  # Hz (Koch has more joints, keeping higher rate)
    
    # Joint State Broadcaster - publishes joint states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Joint Trajectory Controller - accepts trajectory commands
    koch_v11_controller:
      type: joint_trajectory_controller/JointTrajectoryController

koch_v11_controller:
  ros__parameters:
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - pen_holder
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    allow_partial_joints_goal: false
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      
    # PID gains (tune these for your robot)
    gains:
      shoulder_pan:
        p: 100.0
        i: 0.0
        d: 10.0
      shoulder_lift:
        p: 100.0
        i: 0.0
        d: 10.0
      elbow_flex:
        p: 100.0
        i: 0.0
        d: 10.0
      wrist_flex:
        p: 100.0
        i: 0.0
        d: 10.0
      wrist_roll:
        p: 50.0
        i: 0.0
        d: 5.0
      pen_holder:
        p: 50.0
        i: 0.0
        d: 5.0
